-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/routes/localization/

-- Partial translation by Sammore
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Routes", "ptBR")
if not L then return end

L[" Data"] = "Dados"
L[" Gatherer/HandyNotes currently does not support callbacks, so this is impossible for Gatherer/HandyNotes."] = "Gatherer/HandyNotes não suportam \"callbacks\", então é impossivel para Gatherer/HandyNotes."
L["%s - Node %d"] = "%s - Nodo %d"
L["A route with that name already exists. Overwrite?"] = "Já existe uma rota com esse nome. Sobrescrever?"
L["Add"] = "Adicionar"
L["Add node after (green)"] = "Adicionar nota depois (verde)"
L["Add node before (red)"] = "Adicionar nota antes (vermelho)"
L["Always show"] = "Sempre Visivel"
L["Are you sure you want to delete this route?"] = "Você tem certeza que deseja excluir essa rota?"
L["Are you sure you want to recreate this route? This will delete all customized settings for this route."] = "Você tem certeza que deseja recriar esta rota? Isto excluirá todas as configurações personalizadas desta rota"
L["Auto show and hide routes based on your professions"] = "Mostrar e esconder automaticamente baseado em sua profissão"
L["Auto show/hide"] = "Mostrar/Esconder automaticamente"
L["Auto Show/Hide per route type"] = "Mostrar/Esconder automaticamente por rota"
L["Auto Show/Hide settings"] = "Mostrar/Esconder automaticamente configurações"
L["Automatic route updating"] = "Update automático de rota"
L["Background"] = "Plano de Fundo"
L["Cancel route edit"] = "Cancelar edição de Rota"
L["Cartographer_Waypoints module is missing or disabled"] = "Módulo Cartographer_Waypoints não existe ou está desabilitado"
L["Change default hidden route color"] = "Alterar para esconder cor padrão da rota"
L["Change default route color"] = "Alterar cor padrão da rota"
L["Change direction (TomTom)"] = "Alterar direções (TomTom)"
L["Change the line color"] = "Alterar a cor da linha"
L["Color of lines"] = "Cores das linhas"
L["Create Route"] = "Criar Rota"
L["Creating a route"] = "Criando uma rota"
L["Default route"] = "Rota Padrão"
L["Delete"] = "Apagar"
L["Edit route"] = "Editar Rota"
L["Help File"] = "Arquivo de Ajuda"
L["Hide Route"] = "Ocultar Rota"
L["Information"] = "Informação"
L["Line Color"] = "Cor da Linha"
L["Minimap"] = "Minimapa"
L["Optimize Route"] = "Otimizar Rota"
L["Optimizing a route"] = "Otimizando uma Rota"
L["Options"] = "Opções"
L["Recreate Route"] = "Recriar Rota"
L["Route Optimizing"] = "Otimizando Rota"
L["routes"] = "Rotas"
L["Show hidden routes"] = "Mostrar rotas ocultas"
L["Width (Map)"] = "Largura (Mapa)"
L["Width (Minimap)"] = "Largura (Minimapa)"
L["Worldmap"] = "Mapa Global"

