-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/routes/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Routes", "koKR")
if not L then return end

L["Skill-Engineering"] = "기계공학"
L["Skill-Fishing"] = "낚시"
L["Skill-Herbalism"] = "약초 채집"
L["Skill-Mining"] = "채광"

