-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/routes/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Routes", "ruRU")
if not L then return end

L[" Data"] = "Данные"
L[" Gatherer/HandyNotes currently does not support callbacks, so this is impossible for Gatherer/HandyNotes."] = "Gatherer/HandyNotes в данный момент не поддерживают обратные вызовы, т.о. это не возможно для Gatherer/HandyNotes."
L["%s - Node %d"] = "%s - Узел %d"
L["|cffffd200     %d|r node(s) are at |cffffd2000|r yards of a cluster point"] = "|cffffd200     %d|r точек сбора находятся в |cffffd2000|r метрах от указанного места"
L["|cffffd200     %d|r node(s) are between |cffffd200%d|r-|cffffd200%d|r yards of a cluster point"] = "|cffffd200     %d|r точек находятся между |cffffd200%d|r и |cffffd200%d|r метрами от указанного места"
L["A route with that name already exists. Overwrite?"] = "Маршрут с таким именем уже существует. Перезаписать?"
L["A taboo with that name already exists. Overwrite?"] = "Запрещенная зона с таким именем уже существует. Перезаписать?"
L["Add"] = "Добавить"
L["Add node after (green)"] = "Добавить узел после (зеленый)"
L["Add node before (red)"] = "Добавить узел до (красный)"
L["Always show"] = "Всегда показывать"
L["An updated copy of TomTom is required for TomTom integration to work"] = "Для работы интеграции с TomTom требуется обновленная версия TomTom"
L["Archaeology"] = "Археология"
L["Are you sure you want to delete this route?"] = "Вы уверены, что хотите удалить этот маршрут?"
L["Are you sure you want to delete this taboo? This action will also remove the taboo from all routes that use it."] = "Вы уверены, что хотите удалить запретную зону? Это действие также удалит её из всех маршрутов."
L["Are you sure you want to recreate this route? This will delete all customized settings for this route."] = "Вы уверены, что хотите пересоздать этот маршрут? Это удалит все персональные настройки для этого маршрута."
L["Auto show and hide routes based on your professions"] = "Автоматическое сокрытие маршрутов на основе проффесии"
L["Auto show/hide"] = "Автоматическое сокрытие"
L["Auto Show/Hide per route type"] = "Автоматическое скрытие по типу маршрута"
L["Auto Show/Hide settings"] = "Настройки автоматического скрытия"
L["Automatic route updating"] = "Автоматическое обновление маршрута"
L["AUTOMATIC_UPDATE_TEXT"] = [=[Routes автоматически обновляет Ваши маршруты и добавляет/удаляет узлы, когда это требуется, если Вы используете |cffffff78GatherMate|r или |cffffff78Cartographer_<Profs>|r как источники данных. |cffffff78Gatherer/HandyNotes|r не поддерживаются т.к. в данный момент они не поддерживают обратные вызовы.


Когда Вы находите новый узел в любом из этих дополнений, Routes просматривает зону в поисках существующих маршрутов соответствующего типа и вставляет узел в лучьшее место маршрута. Таким же образом, когда Вы удаляете узел в этих дополнениях, Routes также удаляет узел из соответствующего маршрута.

Движение существующего положения узлов на несколько ярдов отрабатывается как удаление узла с последующей его вставкой. Фактически это делается также как и в дополнениях GatherMate и Cartographer_<Profs>.

Для остановки такого автоматического поведения, Вы можете выключить это в настройках следуя следующим шагам:

|cffffff781.|r  Найдите |cffffff78Routes|r в корне дерева слева экрана настроек.

|cffffff782.|r Снимите галочки рядом с соответствующими источниками данных.
]=]
L["Background"] = "В фоне"
L["Background Disclaimer"] = "Это заставляет выполнять создание маршрута в фоне, но несколько медленее чем при блокировании ВоВ. Пожалуйста отметьте себе то, что это заметно снижает производительность ВоВ."
L["Cancel route edit"] = "Отменить редактирование маршрута"
L["Cancel taboo edit"] = "Отменить редактирование запретной зоны"
L["Cartographer_Waypoints module is missing or disabled"] = "Модуль Cartographer_Waypoints отсутствует или отключен"
L["Change default hidden route color"] = "Изменить цвет по умолчанию скрытых маршрутов"
L["Change default route color"] = "Изменить цвет по умолчанию маршрутов"
L["Change direction (TomTom)"] = "Изменить направление (TomTom)"
L["Change the line color"] = "Изменить цвет линии"
L["Color of lines"] = "Цвета линий"
L["Create Route"] = "Создать маршрут"
L["Create Route from Data Sources"] = "Создать маршрут из источников данных"
L["Create Taboo"] = "Создать запрещенную зону"
L["CREATE_BARE_ROUTE_DESC"] = "Это создаст маршрут только с 3 начальными точками в нем, и не будет использовать никаких данных из любых источников. Вы должны будите вручную редактировать маршрут для добавления и удаления узлов."
L["CREATE_ROUTE_TEXT"] = [=[Создание маршрута проходит в 4 простых шага. Первое, найдите |cffffff78Add|r секцию слева.

|cffffff781.|r Введите имя маршрута и нажмите |cffffff78ENTER|r или щелкните по кнопке |cffffff78OK|r.

|cffffff782.|r Выберите локацию для создания в ней маршрута.

|cffffff783.|r Выберите источники данных.

|cffffff784.|r Выберите тип данных использующихся в Вашем маршруте.


|cffffd200Примечания:|r

*Важно нажать  |cffffff78ENTER|r или щелкнуть кнопку |cffffff78OK|r при вводе названия маршрута, иначе он не будет сохранен.

* Если маршрут успешно создан, Вы увидите розовые линии покрывающие выбранную локацию на карте мира. Запись для каждого будет создана слева под надписью Маршруты. Начальный маршрут не оптимизирован и нуждается в оптимизации.
]=]
L["CREATE_TABOOS_TEXT"] = [=[|cffffff78Запрещенные области|r представляют собой области (2D многоугольники) на карте мира, которые позволяют легко дать понять Routes, что они должны быть проигнорированы. Когда такие области определены, Routes активно игнорирует любые узлы в этих областях, и придпринимает дополнительные усилия, чтобы созданные пути не пересекали эти области. Это широко используется для потметки таких мест, через которые нежелательно ходить, а именно парящие острова, пещеры, высокие горы, вражеские города итд.

Запрещенные области создаются при помощи следующих шагов:

|cffffff781.|r Найдите |cffffff78Taboos|r в корне меню на левом экране настроек.

|cffffff782.|r  Введите имя запрещенной области и нажмите |cffffff78ENTER|r или щелкните по кнопке |cffffff78OK|r.

|cffffff783.|r Выберите имя локации в выпадающем списке для создания в ней запрещенной зоны.

|cffffff784.|r Щелкните по |cffffff78Create Taboo|r.

|cffffff785.|r Найдите созданную зону на левой панели настроек в меню |cffffff78Taboos|r.

|cffffff786.|r Щелкните по кнопке |cffffff78Edit taboo region|.

|cffffff787.|r Откройте карту мира и выберите, если необходимо, нужную локацию для запрещенной зоны.

|cffffff788.|r  Вы сможете увидеть треугольную затененную область на карте мира. Отредактируйте запрещенную зону путем
a) |cffffff78Претаскивания|r узлов многоугольника;
b) Добавления узла в многоугольник щелчком  |cffffff78ЛКМ|r между узлами;
c) Удаления узла из многоугольника щелчком |cffffff78ПКМ|r по существующему узлу.

|cffffff789.|r  Щелкните по кнопке |cffffff78Save taboo edit|r чтобы сохранить изменения, или по кнопке |cffffff78Cancel taboo edit|r чтобы не сохранять их.

Запрещенные области могут накладываться друг на друга, пересекаться между собой и содержать любое количество узлов по Вашему желанию. Это значит что Вы можете создавать очень сложные и точные запрещенные области если захотите этого.

 
|cffffd200Примечания:|r

*Однажды созданную запрещенную зону Вы можете прекрепить к существущему маршруту в его настройках. Вы должны заново оптимизировать маршрут после прекрепления или удаления запрещенной зоны из маршрута.

*Редактирование запрещенной зоны будет влиять на все маршруты её использующие, также удаление запрещенной зоны удалит её из всех маршрутов её использующих.
]=]
L["Creating a route"] = "Создание маршрута"
L["Creating a taboo region"] = "Создание запрещенной области"
L["CUSTOMIZING_ROUTE_TEXT"] = [=[Вы можете легко настроить отображение Ваших маршрутов на карте.  Настройки состоят из двух частей. Раздела |cffffff78Options|r слева, содержащего глобальные настройки применяемые к всему,  и настроек |cffffff78Line Settings|r для каждого отдельного маршрута, используемых для изменения настроек, отличных от глобальных настроек.

Для прорисовки карты, Вы уможете указать на каких картах Routes должен отрисовывать Ваши маршруты, также как и их цвет и толщину линий. Дополнительно Вы можете указать должны ли линии на миникарте отображаться пунктиром, накладываться на стрелку слежения и иконки узлов расставленные  |cffffff78GatherMate|r/|cffffff78Cartographer|r/|cffffff78Gatherer|r/|cffffff78HandyNotes|r.

Каждому маршруту с помощью настроек может быть назначен уникальный цвет и толщина линии, он также может быть полностью скрыт. Это позволяет Вам отмечать маршруты , которые Вы больше не хотите использовать, но не хотите удалять из отображения на картах. Настройка |cffffff78Show hidden routes|r в глобальных настройках может быть использована для прекрытия индивидуальной настройки маршрута.

Также Вы можете выбрать |cffffff78Auto show/hide|r  маршруты на основе типа узлов, которые они содержат, такие как узлы горного дела или травничества, а также выбрать отображение маршрута только если Вы владеете данными проффесиями, а также отображение маршрута только при включении данной способности, также всегда отображать маршруты, или никогда их не отображать. Если маршрут


]=]
L["Default route"] = "Маршрут по умолчанию"
L["Delete"] = "Удалить"
L["Delete node"] = "Удалить узел"
L["Delete Taboo"] = "Удалить запрет"
L["Delete this taboo region permanently. This will also remove it from all routes that use it."] = "Навсегда удалить запрещенную область. Это также удалит её из всех маршрутов."
L["Direction changed"] = "Направление изменено"
L["Draw on minimap when indoors"] = "Отображать на миникарте, при нахождении внутри зданий"
L["Edit route"] = "Редактировать маршрут"
L["Edit Route Manually"] = "Редактировать маршрут вручную"
L["Edit taboo region"] = "Редактировать запрещенную зону"
L["Edit this route on the world map"] = "Редактировать маршрут на карте мира"
L["Edit this taboo region on the world map"] = "Редактировать запрещенную зону на карте мира"
L["Extra optimization"] = "Экстра оптимизация"
L["ExtractGas"] = "Газ"
L["ExtraOptDesc"] = "Включение этой опции делает оптимизацию ~40% длительнее, но соданные маршруты становятся немного лучьше. Рекомендуется выключить."
L["FAQ"] = "ЧаВо"
L["Fishing"] = "Рыбалка"
L["Frequently Asked Questions"] = "Часто Зазадаваемые Вопросы"
L["GathererHERB"] = "Травничество"
L["GathererMINE"] = "Горное дело"
L["GathererOPEN"] = "Сокровища"
L["GatherMate2Archaeology"] = "Археология"
L["GatherMate2Extract Gas"] = "Извлечение газа"
L["GatherMate2Fishing"] = "Рыболовство"
L["GatherMate2Herb Gathering"] = "Травничество"
L["GatherMate2Mining"] = "Горное дело"
L["GatherMate2Treasure"] = "Сокровища"
L["Help File"] = "Файл помощи"
L["Herbalism"] = "Травничество"
L["Hidden route"] = "Скрытый маршрут"
L["Hide Route"] = "Скрыть маршрут"
L["Hide the route from being shown on the maps"] = "Скрыть маршрут из отображаемых сейчас на  картах"
L["Information"] = "Информация"
L["Integrated support options for TomTom"] = "Настройки встроенной поддержки для TomTom"
L["Line Color"] = "Цвет линии"
L["Line gaps"] = "Пробелы линии"
L["Line Settings"] = "Настройки линии"
L["Map Drawing"] = "Прорисовка карты"
L["Minimap"] = "Миникарта"
L["Minimap drawing"] = "Прорисовка миникарты"
L["Minimap when indoors"] = "Миникарта внутри зданий"
L["Mining"] = "Горное дело"
L["Name of Route"] = "Название маршрута"
L["Name of Taboo"] = "Имя запрещенной зоны"
L["Name of taboo region to add"] = "Имя запрещенной зоны для добавления"
L["Name of the route to add"] = "Имя маршрута для добавления"
L["Never show"] = "Никогда не показывать"
L["No data found"] = "Данные не найдены"
L["No data selected for new route"] = "Нет данных для нового маршрута"
L["No name given for new route"] = "Не введено имя нового маршрута"
L["No name given for new taboo region"] = "Не введено имя новой запретной зоны"
L["Normal lines"] = "Нормальные линии"
L["Note"] = "Примечание"
L["Now running TSP in the background..."] = "Сейчас оптимизация запущена в фоне...."
L["Only while tracking"] = "Только при слежении"
L["Only with profession"] = "Только для профессии"
L["Optimize Route"] = "Оптимизировать маршрут"
L["Optimizing a route"] = "Оптимизация маршрута"
L["Options"] = "Настройки"
L["Overview"] = "Обзор"
L["OVERVIEW_TEXT"] = [=[ |cffffff78Routes|r это дополнение разработанное для того, чтобы сделать сбор ресурсов более эффективным. Это достигается созданием эффективных путей сбора того, что Вы хотите собрать используя существующие данные из дополнений |cffffff78GatherMate|r, |cffffff78Cartographer_<Profs>|r или |cffffff78Gatherer|r. Эти маршруты отображаются на Ваших картах, что позволяет Вам легко и быстро следовать по ним.

Задача |cffffff78Travelling Salesman Problem|r (TSP) это традиционная задача где дано N городов и даны расстояния между любыми двумя из них, Ваша задача отыскать кратчайший путь для однократного посещения всех городов и вернуться в начальный город. Такая же задача применима к узлам сбора в World of Warcraft для нахождения кратчайшего из возможных маршрутов для посещения каждого узла сбора в цепочке.
]=]
L["Pass %d: %d%%"] = "Проход %d: %d%%"
L["Pass %d: %d%% - %d yards"] = "Проход %d: %d%% - %d ярдов"
L["Path with %d nodes found with length %.2f yards after %d iterations in %.2f seconds."] = "Путь длиной %.2f ярдов из %d узлов  найден после %d итераций за %.2f  секунд."
L["Permanently delete a route"] = "Навсегда удалить маршрут"
L["Recreate Route"] = "Пересоздать маршрут"
L["Recreate this route with the same creation settings. NOTE: This only works for data from GatherMate2 and Gatherer."] = "Пересоздать этот маршрут с теми же настройкамми. ПРИМИЧАНИЕ: Это работает только с данными GatherMate2 и Gatherer."
L["Reset"] = "Сброс"
L["routes"] = "маршруты"
L["Routes with Archaeology"] = "Маршруты с архиологией"
L["Routes with Ore"] = "Маршруты сбора руды"
L["Routes with Treasure"] = "Маршруты сбора сокровищ"
L["Save route edit"] = "Сохранить изменения маршрута"
L["Save taboo edit"] = "Сохранить изменения запрета"
L["Select data to use"] = "Выберите, какие данные использовать"
L["Select data to use in the route creation"] = "Выберите, какие данные использовать для создания маршрута"
L["Select sources of data"] = "Выберите источники данных"
L["Select taboo regions to apply:"] = "Выберите области запрета для:"
L["Select Zone"] = "Выбрать зону"
L["Set the width of lines on each of the maps."] = "Установите толщину линий для всех типов карт."
L["Shorten the lines drawn on the minimap slightly so that they do not overlap the icons and minimap tracking blips."] = "Укоротите линии на миникарте так, чтобы они не перекрывали значки и точки слежения."
L["Show hidden routes"] = "Отображать скрытые маршруты"
L["Show hidden routes?"] = "Отобразить скрытые маршруты?"
L["Skill-Engineering"] = "Навык-Инженерия"
L["Skill-Fishing"] = "Навык-Рыбная ловля"
L["Skill-Herbalism"] = "Навык-Травничество"
L["Skill-Mining"] = "Навык-Горное дело"
L["Taboos"] = "Запретные зоны"
L["Taboos in %s"] = "Запретные зоны в %s"
L["The following error occured in the background path generation coroutine, please report to Grum or Xinhuan:"] = "Во время работы процедуры создания маршрута произошла ошибка, пожалуйста сообщите об этом Grum или Xinhuan:"
L["There is already a TSP running in background. Wait for it to complete first."] = "Процедура оптимизации уже запущена в фоне. Сначала дождитесь её окончания."
L["This route contains |cffffd200%d|r nodes that have been tabooed."] = "Это маршрут содержит |cffffd200%d|r, которые запрещены."
L["This route contains the following nodes:"] = "Это маршрут содержит следующие узлы:"
L["This route has no taboo regions."] = "Это маршрут не содержит запретных областей."
L["This route has the following taboo regions:"] = "Это маршрут содержит запрещенные зоны:"
L["TomTom is missing or disabled"] = "TomTom не установлен или заблокирован"
L["Width (Map)"] = "Ширина (Карта)"
L["Width (Minimap)"] = "Ширина (мини-карта)"
L["Width (Zone Map)"] = "Ширина (карта зоны)"
L["Width of the line in the map"] = "Ширина линии на карте"
L["Width of the line in the Minimap"] = "Ширина линии на мини-карте"
L["Width of the line in the Worldmap"] = "Ширина линии на карте мира"
L["Width of the line in the Zone Map"] = "Ширина линии на карте зоны"
L["Worldmap"] = "Карта мира"
L["Worldmap drawing"] = "Отрисовка карты мира"
L["Yards to move before triggering a minimap update"] = "Метров в пути до обновления мини-карты"
L["You have |cffffd200%d|r route(s) in |cffffd200%s|r."] = "У вас |cffffd200%d|r маршрут(ов) в |cffffd200%s|r."
L["You have |cffffd200%d|r taboo region(s) in |cffffd200%s|r."] = "У вас |cffffd200%d|r запретных областей в |cffffd200%s|r."
L["You may not delete a route that is being optimized in the background."] = "Вы не можете удалить оптимизирующийся маршрут."
L["You may not delete a taboo that is being edited."] = "Вы не можете удалить редактируемый запрет."
L["Zone Map"] = "Карта зоны"
L["Zone Map drawing"] = "Отрисовка карты зоны"
L["Zone to create route in"] = "Зона для создания маршрута"
L["Zone to create taboo in"] = "Зона для создания запрета"

